name: CI/CD Pipeline - Azure App Service

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

   
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

   
    - name: Install Dependencies
      run: npm install

    
    - name: Run Tests
      run: npm test

    
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

   
    - name: Build Docker Image
      run: docker build -t briitzApp:latest .

   
    - name: Push to ACR
      run: |
        docker tag briitzApp:latest briitznewacr.azurecr.io/briitzApp:latest
        docker push briitznewacr.azurecr.io/briitzApp:latest

    
    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: briitzApp
        slot-name: production
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: .
